### ISSUE TITLE
Scoreboard messages

### ISSUE THREAD

**Issue by MacoSVK** [MLG-Fortress/ExtraHardMode#111]
Hi there, is there any way to make scoreboard wider? To make it more clean and readable?
Thanks a lot.

**Comment by MacoSVK** [comment]
Im translated your plugin and i also cant see , where can i translate 'weight' message. Is there any way how to translate it? Btw: sorry for my english, im simple student from slovakia.

**Comment by RoboMWM** [comment]
I haven't touched the scoreboard (partly due to my inexperience with the scoreboard in general) and if I were to work on it, I'd probably scrap it and use packets similar to ScoreboardStats so it doesn't interfere with other scoreboard/team features when being displayed.

As usual, I'll accept PRs on this feature though.
