### ISSUE TITLE
Standing on falling blocks cause continuous damage?

### ISSUE THREAD

**Issue by ParaDLell** [MLG-Fortress/ExtraHardMode#115]
# if blocks should damage player if they hit him directly
    Dmg Amount When Hitting Players: 2

When standing on, say, dirt and you cause a collapse under your feet, players end up taking multiple ticks of damage as they fall with the dirt block, making even a small collapse extremely painful if not deadly. I'm unsure if this is what was intended with this mechanic.

**Comment by RoboMWM** [comment]
Continuously? Or just multiple times?

If multiple times, try testing with just EHM installed - another plugin might be modifying the noDamageTicks of players.

The setting is only a _modifier_ for suffocation damage, by the way - it doesn't cause any extra damage events or actions.

**Comment by ParaDLell** [comment]
Here, it's easier to show than tell: https://puu.sh/yKdnR/fbd54e57e1.mp4
You can make blocks float by using Tall flowers [lilacs, roses, etc] so it's a 2 block tall gap. When you trigger the falling blocks you fall 2 blocks, and take 2 ticks of damage [so 4 hearts]

**Comment by ParaDLell** [comment]
https://puu.sh/yKdPJ/2b17c30791.mp4 also with further testing, it only does it with dirt and cobblestone, not sand.

**Comment by RoboMWM** [comment]
EHM spawns the falling block where the dirt block once was. It seems the MC server reacts to this differently than sand (not sure if this is because of spigot API for falling block spawning) or how EHM is spawning the block is different than how falling sand is "spawned," if at all. I don't know too much about the internals of MC on this one, maybe ask around in the spigot IRC or on the forums? (Going to need someone who knows how to poke around NMS.)

**Comment by RoboMWM** [comment]
So this config option is erroneous and is already covered by the environmental injuries.suffocation modifier. See https://github.com/MLG-Fortress/ExtraHardMode/commit/f66a7e3e47c9f84facd17ba7e6d71650d120b385 for more details (and which should "fix" this issue).
