### ISSUE TITLE
The 1.13 update general bug report and discussion thread

### ISSUE THREAD

**Issue by RoboMWM** [MLG-Fortress/ExtraHardMode#128]
# [Fill out this form to let me know which features to prioritize for a proper 1.13 update!](http://r.robomwm.com/ehmform)

## If you want to be notified of new alpha builds, click the subscribe button the right! 
no I don't get any pretty subscribers stat.

So yea, this codebase is an abstracted mess based on the nearly-removed Item IDs. So getting this to 100% 1.13 compatibility is going to be a fairly arduous and time-consuming undertaking, similar to a rewrite due to its practically complete dependence of IDs and damage/data values in many areas throughout the codebase.

Here's a non-exhaustive list of some things to do if you wanna help out. https://ci.appveyor.com/project/RoboMWM39862/extrahardmode/build/artifacts for the latest development version. Make sure you include the output of `/version ExtraHardMode` when reporting issues!

Also, feel free to chat and/or idle: https://techfortress.robomwm.com/p/plugin-chat-support.html (yes it includes dumcord too...)

**Comment by SlimeDog** [comment]
Thanks for making a start. Note that [https://dev.bukkit.org/projects/fun-hard-mode/files/2628076](https://dev.bukkit.org/projects/fun-hard-mode/files/2628076) returns a 404.

**Comment by SlimeDog** [comment]
I will do some testing. I assume that transferring data from 1.12.2 is a bad idea (although I'll probably try it); we should build anew.

If it's of any use, you can find my config [here](https://blackdog.straight8.com/drops/EHM-config.yml.txt). Please let me know when you have it, or if you don't want it, so it want be removed.

**Comment by SlimeDog** [comment]
Spigot 1.13.1 latest
EHM 1.13-alpha

plugin.yml is missing:
> api-version: 1.13

**Comment by RoboMWM** [comment]
Huh, thought I added that to plugin.yml a while ago. I guess I forgot...

**Comment by RoboMWM** [comment]
I don't mind if you post issues here, the update has a ways to go for few of the features. Will put up a poll later today.

**Comment by RoboMWM** [comment]
Poll added. https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAN__pqYxV1UN0E3R0pWWDhTOFFRTE5NNkNLNjBPMEdKNC4u

**Comment by SlimeDog** [comment]
I tested [mining](#129), [farming](#130), [torch](#131), and [gravity](#132) mechanics. Much more to test. Please feel free to pitch in.

**Comment by SlimeDog** [comment]
Until someone shows otherwise, I'm going so assume that monster attributes have not changed, since they do not involve materials changes. For example:

**Monster attributes**
- More monsters spawn below Y=55.
- Monsters spawn even in partially-lit spaces below Y=40.
- Monsters spawn in previously-visited locations.
- Monsters drop nothing if at great disadvantage (for example, in water or damaged from falling).
- Monster grinders are detected and disabled.

**Blaze attributes**
- Blazes occasionally spawn near bedrock in the overworld, but do not drop any items.
- Blazes spawn more frequently in the nether.
- Blazes drop fire when damaged. Fire is bad (see above).
- Blazes explode when killed, but damage only players, not the environment.
- Blazes drop bonus loot when killed.

**Creeper attributes**
- Creeper explosions damage only players and other entities, not the environment.
- Creepers occasionally drop primed TNT when killed.
- Creepers explode if damaged by fire.
- Charged creepers explode when damaged.

**EnderDragon attributes**
- EnderDragons can respawn.
- EnderDragons drop dragon eggs, and sometimes villager eggs.
- EnderDragons call Blazes and Zombies as minions
- Endermen nearby will sometimes join the fight.
- Players cannot build protective structures in The End.

**Enderman attributes**
- Endermen can teleport the player, as well as themselves.

**Ghast attributes**
- Ghasts explode when killed, but damage only players, not the environment.
- Ghasts are harder to damage and killed, but drop more loot.

**MagmaCube attributes**
- MagmaCubes occasionally spawn with Blazes in the nether.
- MagmaCubes grown into Blazes when damaged.

**PigZombie attributes**
- PigZombies are always angry, but do not cause quite so much damage.
- PigZombies drop netherwart when killed in fortresses, and sometimes elsewhere in the nether.
- PigZombies spawn from lightning strikes in the overworld.

**Skeleton attributes**
- Skeletons sometime shoot snowballs, which cause blindness.
- Skeletons sometime shoot fireballs. Fire is bad (see above).
- Skeletons sometime shoot silverfish, which cause havoc.
- Arrows often pass through skeletons. Close combat is more effective, but more dangerous.

**Spider attributes**
- Spiders drop webs when killed, which slow movement.
- Spiders spawn more frequently underground.

**Witch attributes**
- Witches sometimes spawn baby Zombies to aid their attack.
- Witches sometimes cause explosions.
- Witches can teleport.

**Zombie attributes**
- Zombie hit causes the player to slow for five seconds. Subsequent hits increase the effect.
- Zombies occasionally drop heads and are resurrected when killed. Break the dropped head to stop the cycle.

**Comment by RoboMWM** [comment]
Yea, all this stuff should be unchanged. I think the TemporaryBlock abstraction is based on material string ids instead if integer ids so that one is good. That one's also is used in very few places (only one feature that I know of), so yea.

**Comment by RoboMWM** [comment]
New alpha build has been released! Details on this commit: https://github.com/MLG-Fortress/ExtraHardMode/commit/af6d56d81da8eb3e4b08f31576b6adb2dd586642 (Next time I'll mention this issue on a commit to automatically notify of a new alpha build.)

Download at https://ci.appveyor.com/project/RoboMWM39862/extrahardmode/build/artifacts

**Comment by RoboMWM** [comment]
Todo: Revert inclusion of Redstone torches for placement underground

**Comment by SlimeDog** [comment]
There looks to be a second 3.13-beta.jar. I am confused. **cmp** says they are different.

**Comment by SlimeDog** [comment]
Now that EHM for 1.13.2 is in beta, could the builds go to 
[https://github.com/MLG-Fortress/ExtraHardMode/releases](https://github.com/MLG-Fortress/ExtraHardMode/releases)

**Comment by RoboMWM** [comment]
Idk what cmp is, but yea I did make a few changes before releasing to bukkitdev.

If you can figure out how to make appveyor automatically publish releases (based on a certain commit message?) then I'd be ok with that.

**Comment by SlimeDog** [comment]
Linux **cmp** compares binary files.

I have no idea how to automate releases. But having one unidentified release at .../artifacts/ is not ideal for users. (Also not a good idea to use the same version for two releases.)

Perhaps the comment could identify the version. That would help a lot.

**Comment by RoboMWM** [comment]
Well I can add commit hash to version if it matters; since there's not a lot of users using this plugin (or at least these dev builds), I haven't bothered to do that. But I suppose I can add it.

**Comment by SlimeDog** [comment]
Thanks. I'm trying to be religious about testing. Anything that makes life easier is good. :)
