### ISSUE TITLE
Blazes will only explode in the overworld.

### ISSUE THREAD

**Issue by Weasel-Beans** [MLG-Fortress/ExtraHardMode#170]
With my settings like this:

    Blazes Explode On Death:
      Enable: true
      Below Border:
        Explosion Power: 2
        Set Fire: true
        World Damage: true
      Above Border:
        Explosion Power: 2
        Set Fire: true
        World Damage: true

Blazes will only explode in the overworld, not the Nether or End.

**Comment by RoboMWM** [comment]
Is the plugin enabled in the nether?

**Comment by Weasel-Beans** [comment]
Yes, the plugin is enabled in all worlds, and all the other settings related to the nether like pigmen being hostile, blazes spawning/splitting, etc. seem to be working properly. And after testing it just now, blazes don't explode in The End either when it's enabled

**Comment by Weasel-Beans** [comment]
Here's my full config as it is set up right now: https://pastebin.com/76biqVnm

Explosions are not disabled by any other plugin

**Comment by RoboMWM** [comment]
Hmm, it seems that blazes respond differently in the nether vs. the overworld, and this is by design. I'm guessing part of it is so the drops aren't destroyed (explosions destroy dropped entities).

https://github.com/MLG-Fortress/ExtraHardMode/blob/c368c2a3a231dd9c2172b9d8f862c49a44f4a8a6/src/main/java/com/extrahardmode/features/monsters/Blazes.java#L139-L178
