### ISSUE TITLE
api-version:1.14 does cannot run on Spigot 1.13.2

### ISSUE THREAD

**Issue by SlimeDog** [MLG-Fortress/ExtraHardMode#174]
Spigot 1.13.2 final
ExtraHardMode 3.14.alpha-f00ecfd

> api-version: 1.14

is not supported in Spigot 1.13.2. Use
> api-version: 1.13

if support for 1.13.2 is intended. If support for only 1.14.x is intended, then no change is needed, other than notation of that fact.

**Comment by RoboMWM** [comment]
Yes, 1.14 support is intended here. I think I may have already started using the new Materials which 1.13 isn't aware of.

I guess I could look into trying to update plugins without using a newer API, but IMO it'll just make the eventual-needed updating a lot harder to do when a new feature or otherwise necessitates updating.
