### ISSUE TITLE
Block Place Event error

### ISSUE THREAD

**Issue by erdrickk** [MLG-Fortress/ExtraHardMode#26]
getting this with the latest version and the latest build of Spigot http://hastebin.com/ilihikuyig.avrasm

**Comment by erdrickk** [comment]
looking at the error more it seems to have something to do with Terrain Control and a custom Biome that I've made.

**Comment by RoboMWM** [comment]
Hmm... not sure if this is possible, since it's just flat out throwing an exception if it can't return the biome in the Spigot API... so not sure how I'll go about this at the moment - I wonder if there's other ways to get the biome name without having to do getBiome(). https://github.com/MLG-Fortress/ExtraHardMode/blob/master/src/main/java/com/extrahardmode/features/Tutorial.java#L266

**Comment by RoboMWM** [comment]
That'd require me adding it as a dependency, which I wouldn't want to do nor should do anyways since those biomes are entirely custom.

**Comment by erdrickk** [comment]
The error doesn't seem to be damaging to the game play itself, everything still seems to work. Is there a way to just suppress the error?

**Comment by RoboMWM** [comment]
That was my intent, and a try-catch statement should do that.

**Comment by RoboMWM** [comment]
Please try 3.7.2, and comment here if you're still having issues.

If you don't know how to reproduce, try placing a dirt block in your custom biome. Make sure you're in a mode where ExtraHardMode applies to you (i.e. not op, and in survival mode).
