### ISSUE TITLE
Apply torch rules to redstone torches

### ISSUE THREAD

**Issue by PsychoLynx** [MLG-Fortress/ExtraHardMode#32]
Hi there!

If possible, I would like an option to have the (redstone)torches pop off the ground immediately when exposed o rain (can be a custom probability, which I'd set to 100% or something). Also, it would be nice to have redstone torches also obey to "no placement on soft surfaces" option

**Comment by RoboMWM** [comment]
Probably will have to make this configurable, as I'm unsure of use cases for redstone torches in some machines.

As for torches being exposed to rain, this task is not immediate to reduce impact on lag (since in order for it to be immediate, it'd have to scan all chunks at once). Will see if any sort of config for this would make any sense - perhaps I guess a % chance whether to actually remove torches when the interval scans a new chunk (would obviously not have it scan the chunk if it decides not to obviously, didn't know of a better way to explain this.)

**Comment by RoboMWM** [comment]
@PsychoLynx Do you want configurable probability solely to give it a 100% chance of torches popping off?

**Comment by PsychoLynx** [comment]
@RoboMWM I'm a fan of configurability, but I suppose a true/false works well for my personal intentions :) The probability came from an idea of sort of a "slow decay" of torches every time it rain, in case in testing the 100% chance ends up being too punishing or something.

**Comment by RoboMWM** [comment]
> The probability came from an idea of sort of a "slow decay" of torches every time it rain, in case in testing the 100% chance ends up being too punishing or something.

This is its current design. It only checks one chunk every x minutes or so to avoid lag, and obviously only applies to loaded chunks.

**Comment by RoboMWM** [comment]
So redstone torches probably weren't considered since Big_Scary [specifically focused on torches.](https://dev.bukkit.org/projects/fun-hard-mode?comment=35)

But I agree, it makes sense for these rules to apply here for general torches.

**Comment by RoboMWM** [comment]
This should be part of the 3.13.alpha.2 build.
