### ISSUE TITLE
Support for 1.20.X?

### ISSUE THREAD

**Issue by lisbonjoker** [MLG-Fortress/ExtraHardMode#323]

**Comment by RoboMWM** [comment]
make issues for things that don't work.

**Comment by lisbonjoker** [comment]
> make issues for things that don't work.

What you mean, do not work?

**Comment by RoboMWM** [comment]
sorry, I mean that you should create new tickets for bugs you encounter.

Due to how the Bukkit API is designed, plugins generally should be forward-compatible - that is, as long as they are using the Bukkit API (or derivatives like spigot, purpur, paper, etc.), the plugin should work on newer versions.

**Comment by lisbonjoker** [comment]
> sorry, I mean that you should create new tickets for bugs you encounter.
> 
> Due to how the Bukkit API is designed, plugins generally should be forward-compatible - that is, as long as they are using the Bukkit API (or derivatives like spigot, purpur, paper, etc.), the plugin should work on newer versions.

Ah okay, thank you, sorry the latest versions on the spigot plugin page weren't added, so I wasn't sure if it would work!
