### ISSUE TITLE
Explosion effects strip half-slab wood of wood-type

### ISSUE THREAD

**Issue by Romaq** [MLG-Fortress/ExtraHardMode#69]
I set off an explosion over birch half-slab floor. The explosion effect propelled blocks as expected, but converted them to oak half-slab. It is likely all non-oak slabs are stripped of their wood-type when moved by explosions.

**Comment by RoboMWM** [comment]
I took a quick look through the code, and it seems to be passing the original block's data (albeit a deprecate method, likely because of magic values). I'm assuming this happens to the blocks that are thrown up in the air (not the ones that are supposed to fall because blocks were broken underneath it), correct?

**Comment by Romaq** [comment]
I apologize for the delay responding. Yes, blocks thrown up in the air and landing on the ground are stripped of their wood type, defaulting to Oak. I've not tested the revision yet. I'll slate explicit testing tomorrow for this and any other bugs I'm aware of on EHM.

**Comment by RoboMWM** [comment]
as mentioned above, I likely have already fixed this. Please try 3.11
