### ISSUE TITLE
Zombie heads will replace ladders

### ISSUE THREAD

**Issue by manmadehuman** [MLG-Fortress/ExtraHardMode#98]
User reported that in a room with ladders, if a zombie head drops after a zombie kill, it sometimes chooses a block that replaces a ladder and the ladder item vanishes.

**Comment by RoboMWM** [comment]
Hmm so, how do you think we should go about this? (Just asking for input, in case you read that with an aggressive tone lol.) Not spawn a zombie head at all if the block is not air? Afaik the code is looking for a zombie head to determine if they should respawn (old behavior was that they'd respawn if they weren't killed while on fire).

**Comment by manmadehuman** [comment]
To be honest. This was one complain from one person and I've never had issues. He wanted me to post about it.   If it's not a simple fix I wouldn't worry about it. 

The only other complaint about zombie heads I've heard is if they spawn on someone's claimed property (we use GriefPrevention) then they can't break the head.    But even then. It's not game breaking thing.

**Comment by RoboMWM** [comment]
Currently the zombie heads only try to avoid replacing "half blocks" and the like (slabs and such). If there's a block other than air in the location the zombie was (since in the case of a slab, they will still be considered inside that block location), it will place the skull one block higher (since it assumes the zombie was not stuck inside a block when killed by the player).

As for the other - I should be able to do something about that.
